name: Move Major Version Tag on Release

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  move_major_version_tag:
    runs-on: ubuntu-24.04
    steps:

      - uses: cgrindel/gha_select_value@v1
        name: Resolve Release Tag
        id: resolve_release_tag
        with:
          value0: ${{ github.event.release.tag_name }}
          value1: ${{ github.event.inputs.release_tag }}

      - uses: cgrindel/gha_select_value@v1
        name: Resolve Checkout Ref
        id: resolve_checkout_ref
        with:
          value0: ${{ github.ref }}
          value1: v1

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - uses: cgrindel/gha_configure_git_user@v1

      - uses: ./
        name: Move Major Version Release Tag
        with:
          release_tag: ${{ steps.resolve_release_tag.outputs.selected_value }}
          checkout_ref: ${{ steps.resolve_checkout_ref.outputs.selected_value }}
