name: Move Major Version Tag on Release

on:
  release:
    types: [ published ]

jobs:
  move_major_version_tag:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          release_tag: ${{ github.event.release.tag_name }}
